### ISSUE TITLE
configuration help

### ISSUE THREAD

**Issue by mlava** [storvik/pythonremote#1]
Hi there.
Thanks for your work on this, I suspect I am going to find it very helpful!
I am having some problems with setup...

I have tried to add the link to my PATH but getting an error. This is the ln command I tried: 
ln -s /volume1/homes/mark/scripts/pythonremote/pythonremote.py /usr/bin/pythonremote

With autoremoteserver command I get 'autoremoteserver: not found'

I have the script running if In use python3 pythonremote.py.
What is the id that is requested in the configuration steps?

Any suggestions? Thanks again!

**Comment by storvik** [comment]
Hello! 
Due to lack of spare time this project has been going slow lately, but just tested it and it seems to be working. 

Which platform are you using, looks like Linux of some sort? I have tested the program on Mac OsX, Ubuntu and Debian (raspbain). 

Suggest adding the symlink to `/usr/local/bin` or, as I do it, symlink it to a script folder and adding that folder to path. Ex: `export PATH=$PATH:/Users/storvik/Dropbox/scripts:$PATH`. 
After that you could execute `pythonremote` and the initial process should start. 
Remember to exit the shell, or do a `source .bashrc` to reload the changes. 

As for the ID configuration, this could be set to whatever. My Macbook is configured like:
- ID: macbookpro
- Name: Storviks Mackbook Pro
- Sender: Storvik
- Icon: mac

Then run `registerdevice` and register your phone/tablet, and your computer should show up in the device list in autoremote. 

Another note: Sending messages from your device to the computer is only possible when on the same network. However the other way around works. For example I use it to send a message to the phone every time the server is backed up. 

Hope it helps!

**Comment by mlava** [comment]
Thanks!
I have discovered that on my Synology NAS the PATH gets overwritten on login to shell, so I've now made the path change permanent.
Nonetheless, although the server is running, the command 'autoremoteserver help' I get the error autoremoteserver: not found

Any further ideas?

**Comment by storvik** [comment]
Ah, I finally get what's going on here. The readme file hasn't been updated since the name change from autoremoteserver to pythonremote. 

Just type `pythonremote help` instead, and it should work.

**Comment by mlava** [comment]
:-)

I am away from server but will try tonight.
One step closer to my openhab house talking to my tasker-enabled devices...
Thanks for all your help!

**Comment by storvik** [comment]
No problem! Hope it works :smile:

**Comment by mlava** [comment]
Yep, it works fine.
Thanks, I can now use command line from openhab to send messages/notifications to my android devices... :)
